# Generated by Django 4.1.7 on 2023-04-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('companyImage', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
