# Generated by Django 4.1.7 on 2023-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='company',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='companyImage',
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_images'),
        ),
    ]
