# Generated by Django 4.1.7 on 2023-04-10 09:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blogpost_contact_created_at_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_area',
            field=tinymce.models.HTMLField(),
        ),
    ]
